config/routes.rb
FriendCircle::Application.routes.draw do
  root :to => "users#feed"

  resources :users, :only => [:new, :create, :edit, :update]

  resource :session, :only => [:new, :create, :destroy] do
    get "/forgot_password", :to => 'sessions#forgot_password'
    post "/forgot_password", :to => 'sessions#mail_password'
    get "/reset_password/:token", :to => 'sessions#reset_password'
  end

  resources :circles

  resources :posts, :only => [:new, :create, :destroy] do
    resources :upvotes, :only => [:create]
  end

  resources :upvotes, :only => [:destroy]

  get "/feed", :to => "users#feed"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :integer          not null, primary key
#  email                :string(255)      not null
#  password_digest      :string(255)      not null
#  session_token        :string(255)      not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  password_reset_token :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password
  validates :email, :password_digest, :session_token, :presence => true
  validates :password, :presence => true,
                       :length => { :minimum => 6 },
                       :on => :create

  before_validation :reset_session_token, :on => :create

  has_many :friend_circle_memberships, :inverse_of => :user
  has_many :circles, :through => :friend_circle_memberships
  has_many :owned_circles, :class_name => "Circle"
  has_many :authored_posts, :foreign_key => :author_id, :class_name => :post
  has_many :posts, :through => :circles


  def self.find_by_credentials(email, password)
    user = self.find_by_email(email)
    if user && user.is_password?(password)
      user
    end
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    reset_session_token
    self.save!
  end

  def password=(password)
    @password = password

    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def set_password_reset_token!
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_logged_in, :only => [:edit, :update, :feed]

  def new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      login! @user
      redirect_to feed_url
    else
      flash.now[:notices] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])

    render :edit
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to feed_url
      @user.set_password_reset_token!
    else
      flash.now[:notices] = @user.errors.full_messages
      render :edit
    end
  end

  ORDERS = {'new' => 'created_at', 'best' => 'score'}

  def feed
    order_by = ORDERS[params[:order]] || 'score'


    @posts = current_user.posts
                         .includes(:links)
                         .includes(:author)
                         .includes(:upvoters)
                         .order("#{order_by} DESC")
                         .uniq
    render :feed
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Edit password!</h2>

Hint: it hashes to this: <%= @user.password_digest %>

<form method="POST" action=<%= user_url(@user) %> >
  <input type="hidden" name="_method" value="put">

  <label for="user_password">Password</label>
  <input type="password" id="user_password" name="user[password]">
  <br>
  <input type="submit" value="Save Changes">
</form>

app/views/users/feed.html.erb
<%= link_to "Your Circles", circles_url %>
<br>
<br>
<%= link_to "Make a Post!", new_post_url %>

<h2><%= "#{current_user.email}'s feed"%></h2>
 Order By:
 <%= link_to "Best", feed_url(:order => 'best') %>
 <%= link_to "New", feed_url(:order => 'new') %>
<br>
	<%= render "posts/post"%>

app/views/users/new.html.erb
<form method="POST" action=<%= users_url %> >
  <label for="user_email">Email</label>
  <input type="text" id="user_email" name="user[email]">
  <br>
  <label for="user_password">Password</label>
  <input type="password" id="user_password" name="user[password]">
  <br>
  <input type="submit" value="Sign Up">
</form>