config/routes.rb
FriendCircle::Application.routes.draw do
  root :to => "users#feed"

  resources :users, :only => [:new, :create, :edit, :update]

  resource :session, :only => [:new, :create, :destroy] do
    get "/forgot_password", :to => 'sessions#forgot_password'
    post "/forgot_password", :to => 'sessions#mail_password'
    get "/reset_password/:token", :to => 'sessions#reset_password'
  end

  resources :circles

  resources :posts, :only => [:new, :create, :destroy] do
    resources :upvotes, :only => [:create]
  end

  resources :upvotes, :only => [:destroy]

  get "/feed", :to => "users#feed"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string(255)      not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  attr_accessible :body, :circles, :circle_ids
  validates :author, :body, :presence => true

  belongs_to :author, :class_name => "User"
  has_many :post_shares, :inverse_of => :post
  has_many :circles, :through => :post_shares
  has_many :links, :inverse_of => :post
  has_many :upvotes
  has_many :upvoters, :through => :upvotes, :source => :user

  accepts_nested_attributes_for :post_shares
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_logged_in


  def new
    @circles = current_user.circles
    render :new
  end

  def create
    @post = Post.new(params[:post])
    @post.score = 0
    @post.author = current_user
    links = params[:links].values.reject{ |value| value["url"].empty? }
    @post.links.new(links)
    if @post.save
      redirect_to feed_url
    else
      flash.now[:notices] = []
      flash.now[:notices].concat(@post.errors.full_messages)
      @post.links.each do |link|
        flash.now[:notices].concat(link.errors.full_messages)
      end
      @circles = current_user.circles
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to feed_url
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<form action=<%= posts_url %> method="POST">
	<label for="post_body">Post Body</label>
	<input type="text" id="post_body" name="post[body]">
	<h5>Links</h5>
	<ul>
		<% 3.times do |link_number| %>
		<li>
			<label for="<%= "link_#{link_number}" %>">Link</label>
			<input type="text" id="<%= "link_#{link_number}" %>"
				name="<%= "links[#{link_number}][url]" %>">
		</li>
		<% end %>
	</ul>
	<h5>Friend Circles</h5>
  <ul>
		<input type="hidden" name="post[circle_ids][]" value="">
    <% @circles.each do |circle| %>
      <li>
        <label for="circle_<%= circle.id %>"><%= circle.name %></label>
        <input type="checkbox" id="circle_<%= circle.id %>"
          name="post[circle_ids][]" value="<%= circle.id %>">
      </li>
    <% end %>
  </ul>
	<input type="submit" value="Submit Post">
</form>

app/views/posts/_post.html.erb
<ul>
	<% @posts.each do |post| %>
		<li>
			<p><%="#{post.body} -- Score: #{post.score}"%><p>
			<p><%= post.author.email%></p>
			<% if post.author == current_user %>
				<%= button_to "Remove Post", post_url(post), :method => :delete%>
			<% end %>
			<% unless post.upvoters.include?(current_user) %>
				<%= button_to "Upvote", post_upvotes_url(post), :method => :post%>
			<% end %>
			<ul>
				<% post.links.each do |link| %>
				<li><%= link_to link.url, link.url %></li>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

app/views/posts/new.html.erb
<%= render "form" %>