config/routes.rb
FriendCircle::Application.routes.draw do
  root :to => "users#feed"

  resources :users, :only => [:new, :create, :edit, :update]

  resource :session, :only => [:new, :create, :destroy] do
    get "/forgot_password", :to => 'sessions#forgot_password'
    post "/forgot_password", :to => 'sessions#mail_password'
    get "/reset_password/:token", :to => 'sessions#reset_password'
  end

  resources :circles

  resources :posts, :only => [:new, :create, :destroy] do
    resources :upvotes, :only => [:create]
  end

  resources :upvotes, :only => [:destroy]

  get "/feed", :to => "users#feed"

end

app/models/circle.rb
# == Schema Information
#
# Table name: circles
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Circle < ActiveRecord::Base
  attr_accessible :name, :user_id, :friend_circle_memberships, :member_ids

  validates :name, :user, :presence => true
  # validates_uniqueness_of :name, :scope => :user_id

  has_many :friend_circle_memberships, :inverse_of => :circle
  has_many :members, :through => :friend_circle_memberships, :source => :user
  belongs_to :user
  has_many :post_shares
  has_many :posts, :through => :post_shares

  accepts_nested_attributes_for :friend_circle_memberships
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_filter :require_logged_in

  def index
    @user = current_user
    @circles = @user.circles
    render :index
  end

  def new
    @user = current_user
    @members = [current_user]
    @users = User.all
    @circle = Circle.new
    render :new
  end

  def create
    @circle = Circle.new(params[:circle])
    @circle.user = current_user

    flash.now[:notices] = []
    if @circle.save
      redirect_to circle_url(@circle)
    else
      @users = User.all
      @members = @circle.members

      flash.now[:notices].concat(@circle.errors.full_messages)

      @circle.friend_circle_memberships.each do |membership|
        flash.now[:notices].concat(membership.errors.full_messages)
      end

      render :new
    end
  end

  def show
    @circle = Circle.find(params[:id])
    @members = @circle.members
    @posts = current_user.posts
                         .includes(:links)
                         .includes(:author)
                         .order("created_at DESC")
    render :show
  end

  def edit
    @circle = Circle.find(params[:id])
    @users = User.all
    @members = @circle.members
    p @members
    render :edit
  end

  def update
    @circle = Circle.find(params[:id])
    @members = @circle.members
    flash.now[:notices] = []
    if @circle.update_attributes(params[:circle])
      redirect_to circle_url(@circle)
    else
      @users = User.all
      @members = @circle.members

      flash.now[:notices].concat(@circle.errors.full_messages)

      @circle.friend_circle_memberships.each do |membership|
        flash.now[:notices].concat(membership.errors.full_messages)
      end

      render :edit
    end
  end

end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/views/circles/_form.html.erb
<% action_url = @circle.persisted? ? circle_url(@circle) : circles_url %>

<form action=<%= action_url %> method="POST">
  <% if @circle.persisted? %>
    <input type="hidden" value="PUT" name="_method">
  <% end %>
  <label for="circle_name">Circle Name</label>
  <input type="text" id="circle_name" name="circle[name]"
    value="<%= @circle.name %>">
  <ul>
		<input type="hidden" name="circle[member_ids][]" value="">
    <% @users.each do |user| %>
      <li>
        <label for="user_<%= user.id %>"><%= user.email %></label>
        <input type="checkbox" id="user_<%= user.id %>"
          name="circle[member_ids][]" value="<%= user.id %>"
          <%= "checked" if @members.include?(user) %>>
      </li>
    <% end %>
  </ul>

  <% submission_label = @circle.persisted? ? "Save Changes" : "Create Circle"%>

  <input type="submit" value=<%= submission_label %>>
</form>

app/views/circles/edit.html.erb
<h2>Edit Circle <%= @circle.name %></h2>

<%= render "form" %>

app/views/circles/index.html.erb
<%= link_to "Your Feed", feed_url %>
<br>
<br>
<%= link_to "Make a Post!", new_post_url %>

<h2>Your Circles</h2>
<br>


<ul>
  <% @circles.each do |circle| %>
    <li>
      <%= link_to circle.name, circle_url(circle) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Circle", new_circle_url %>

app/views/circles/new.html.erb
<h2>New Circle</h2>

<%= render "form" %>

app/views/circles/show.html.erb
<h2><%= @circle.name%></h2>

<ul>
	<% @members.each do |member| %>
	<li><%= member.email %></li>
	<% end %>
</ul>

<%= link_to "Edit this circle", edit_circle_url(@circle) %>

<%= render "posts/post" %>